### ISSUE TITLE
The input view is not update properly, after reset the model.

### ISSUE THREAD

**Issue by romelgomez** [Trustroots/trustpass#4]
After reset the model, the input view value still there.  

See the video first: https://youtu.be/4owD5bt7Ya0

https://jsfiddle.net/venezuela/5xdtvzcd/

**Comment by simison** [comment]
Thanks @romelgomez! Bonus points for the fiddle.

**Comment by simison** [comment]
This is now fixed with latest v0.4.0. 

See it working from [the demo](https://trustroots.github.io/trustpass/).
